run:
	go run beholder.go bullets.go platform.go player.go main.go --vsync --draw-wires

build-windows:
	GOOS=windows GOARCH=amd64 go build -o demo.exe .

build-linux:
	GOOS=linux GOARCH=amd64 go build -o demo .